### ISSUE TITLE
gps is blank after install

### ISSUE THREAD

**Issue by plapin751** [pimarc/pms50-gns530#10]
i just unzipped the folder for the first time in steam community folder

when i restarted sim.  GPS's  is dark in 172 plane

i rebooted the system, i tried a different aircraft, i tried to re install, read docs

i delete the files out of the folder and the GPS goes back to standard msfs2020 GPS

**Comment by pimarc** [comment]
Hello

You have probably downloaded the sources and not the release.
Please use the link in the Installation section of the documentation.

**Comment by plapin751** [comment]
I tried one called master and also the data one.. looks like i missed the plain one .. thank you for your time ill go donate to cover your time.  because I'm an idiot

**Comment by pimarc** [comment]
You are not and I'm happy when I can help.
Thanks.
