### ISSUE TITLE
GNS 530/430 screens are dark on startup

### ISSUE THREAD

**Issue by sebastianbk** [pimarc/pms50-gns530#12]
Hello,

First of all, thank you for all of your effort in developing this mod. Given the level of detail in your GitHub repo, I'm very excited to try out this GNS 530 improvement.

I downloaded the ZIP file from the Releases page (`v1.0.27`) and placed it in my Community folder. See the screenshot below.

![Community](https://user-images.githubusercontent.com/660576/107141395-b880f700-6928-11eb-8a50-b235421ca6b9.png)

However, when I start up a flight in the Cessna 172, the screens of the GNS 530/430 do not turn on.

![172](https://i.imgur.com/AwY12LY.jpg)

I've read through all of your instructions and I can't see how I should install the mod differently. Do you know what the cause of this issue may be?

I'm running the most up-to-date version of the sim and of Windows 10. The only other non-scenery mods I have installed are the Working Title G1000 and G3000 mods. I tried removing them and restarting the sim but that, unfortunately, did not solve the issue.

**Comment by sebastianbk** [comment]
I just saw you had written some instructions for filing bug reports. I followed all of your suggested steps (removed all other mods, set the weather to clear, restarted my computer, etc.). However, I still encounter the issue. Is there anything obvious I'm missing?

**Comment by pimarc** [comment]
Are you sure you have downloaded the correct package?
This is typically what occurs when you download sources instead of the release.
Please remove the mod from the community folder and install the last release that you will find here:
https://pms50.com/fs2020/gns530/pms50-gns530.zip

**Comment by sebastianbk** [comment]
Thanks for the quick response, @pimarc. Much appreciated!

I did install the correct version. That wasn't the issue. However, I did get it to work. It turns out that if I turn on Live Weather and Live Traffic, the screens won't come on. If I select a weather preset and no traffic, they work fine. Are these live features not supported?

**Comment by pimarc** [comment]
Strange behavior.
There is no relationship here between the GPS and the live weather or traffic.
The Mod works with both ON and most people use it with these conditions.
Do you have some other Mods installed ?
