### ISSUE TITLE
GNS Mod turns on Autopilot

### ISSUE THREAD

**Issue by dissy409** [pimarc/pms50-gns530#15]
When using the GNS mod V1.0.27 in the C172 Skyhawk the autopilot is automatically turned on when the avionics are turned on. It is impossible to turn the auto pilot off either on the panel or via the disengage autopilot button I have on my honeycomb alpha (disconnects as long as I have the button pressed). This does not happen if I remove the mod.

**Comment by pimarc** [comment]
Hi,
I cannot reproduce that issue. The GPS do not send any command to the autopilot.
Are you sure you don't have another MOD or livery installed? Please try without them.
Some users have reported issues with liveries that provide incorrect configuration files.
Maybe you can ask on the forum? https://forums.flightsimulator.com/t/gns530-mod/296598
