### ISSUE TITLE
Black GNS530 after installing the mod

### ISSUE THREAD

**Issue by bam2000** [pimarc/pms50-gns530#16]
Hello,
my GNS530 stays black after installing this mod.
Can you please help me get it to work?
When i remove the mod the GNS530 is working just fine. Using the C172 Classic.

**Comment by pimarc** [comment]
The sim update 3 has broken things as usual.
I will check that.

**Comment by trend900** [comment]
Can you tell us if they fixed anything on the units? It doesn't seem like they did.

**Comment by pimarc** [comment]
I don't know for now. I've just uploaded the update. Let me some time for analyzing.

**Comment by pimarc** [comment]
Thanks to you. There will be a beta release tomorrow that fixes the main things with sim update 3. Now there can have other bugs but anyway you should be able to fly again with the MOD.

**Comment by pimarc** [comment]
Release 1.0.28 available. This a temporary before I'm able to check all the differences afters sim update 3.

**Comment by gunstrife** [comment]
> Release 1.0.28 available. This a temporary before I'm able to check all the differences afters sim update 3.

@pimarc not sure if anyone else is experiencing this but when I unzip 1.0.28 in the community folder, the mod doesn't seem to be enabled.  I still have the default 530 in the Cessna 172

**Comment by gunstrife** [comment]
Works wonderfully!  Stupid question, LPV is not working yet in MSFS 2020 right?  We're not supposed to get a vertical glideslope yet for RNAV approaches on the CDI right?

**Comment by pimarc** [comment]
RNAV vertical guidance works fine with MSFS. You must be at the correct altitude at the IAF and the approach mode must be activated on the autopilot. In some airplanes (ex carenado m20R) there is no glidescope in RNAV... But it works.

**Comment by bam2000** [comment]
Thanks your hotfix version is working :)
