### ISSUE TITLE
GNS 430 is not turning on in Cessna 172 (but the GNS 530 is)

### ISSUE THREAD

**Issue by sebastianbk** [pimarc/pms50-gns530#19]
Hi,

I have previously posted a question here and you were very responsive in helping me resolve the issue I had. Thank you very much for that! Now, I have encountered a new issue with the latest version (`1.0.28`) combined with Sim Update 3 (`1.14.5.0`).

I enjoy flying the Cessna 172 with your add on as it provides a cool balance of old school flight instruments combined with some comfort of modern technology. However, with the most recent versions of the sim and your add on, I can't get the 430 to turn on in the Cessna 172.

I have tried a cold and dark start, a start ready for take off on the runway, and a flight starting mid-air. The behavior is always the same -- the 530 turns on well and works but the 430 doesn't.

I use your data mod and have set the following settings in `config.json`:

```json
{
  "weather_radar": "on",
  "weather_legend": "on",
  "metar_avwx_token": "REDACTED",
  "metar_decode": "on"
}
```

You can see a screenshot of the issue below.

![Screenshot](https://i.imgur.com/xgCSRE3.jpg)

Can I provide any other information that could help you resolve this bug?

Once again, thank you very much for all of your effort and sharing this project with us. It is greatly appreciated! 🙏

**Comment by pimarc** [comment]
Do you have some other mods or liveries installed?
If yes, retry after removing them.
Also be sure to have installed the release and not the source (see install in the documentation)

**Comment by sebastianbk** [comment]
Yes, I do have the latest version installed (`v1.0.28`) from the Releases page. I have had so many issues after Sim Update 3 (incl. problems with Working Title's mods) that I had already removed all of my addons except for your mod.

I just went through my checklists and, when getting ready to taxi, I brought up the ATC menu, which immediately caused the radios and the 530 to crash.

![image](https://user-images.githubusercontent.com/660576/110771364-b3ca9e00-825a-11eb-96fb-802f52e3e15c.png)

Interestingly, yesterday I experienced a similar issue with WT's G1000 mod, which would crash when I would call ATC to request takeoff. This caused me to remove their mod but now I'm starting to think that the radios might have an influence on these crashes?

**Comment by pimarc** [comment]
Do you have some extra liveries installed?

**Comment by sebastianbk** [comment]
No. This is the only content in my Community folder.

![image](https://user-images.githubusercontent.com/660576/110776046-e7f48d80-825f-11eb-8a1e-1f42220c8016.png)

**Comment by pimarc** [comment]
What are the exact steps to reproduce the issue?
I tried with the Cessna and everything works fine here even when I display the ATC menu.

**Comment by sebastianbk** [comment]
I just tried to restart my computer and load up a free flight again (from GCLB to GCXO, if that matters). The behavior seems to be a bit random. This time the 430 did turn on but, when I got to the runway, both the 430 and 530 crashed again with no way to restart them.

Can there be something in a cache somewhere (maybe some data from another mod I had installed previously) that could cause this?

While I do appreciate Asobo and their continued investment in providing updates, it gets a little tedious that literally everything breaks every time they release a new patch.

**Comment by pimarc** [comment]
I cannot reproduce that issue here.
Now the v1.0.28 is a temporary version made just to correct black screens after the sim update 3.
A new version will be available before the end of the week.
Try to see if other users have the same issue by posting on the forum. This may help me.
https://forums.flightsimulator.com/t/gns530-mod

**Comment by sebastianbk** [comment]
Alright, thank you very much!

I will try your new update later this week. Hopefully, that will resolve the issue.

**Comment by pimarc** [comment]
Hi
There is a new release 1.0.29.
Please try it and let me know.
Be careful to not install the sources instead of the release (see "installation" in the documentation)

**Comment by pimarc** [comment]
Hi
Does it work now?

**Comment by pimarc** [comment]
No feedback from the user so I close the case
