### ISSUE TITLE
problems in config.json

### ISSUE THREAD

**Issue by tuxuera** [pimarc/pms50-gns530#22]
First of all congratulate you for your work.

Secondly I have a doubt.
where to put the config.json file to activate the radar ect.... 
-I have changed the name exemple_config.json to config.json. it does not work.
-I have changed all the options, as I understand from your instructions.

these are my parameters and they don't work:

 **{
  "weather_radar": "on",
  "weather_legend": "on",
  "metar_avwx_token": "WAIS_ZrYpkwAGLKnIPVoPNmqftqrS5sZHAId79GakmY
",
  "metar_decode": "on"
}**

I can only think that the config.json file has to be put in another location maybe?

I would like to know how it works, thank you very much for your attention.

Translated with www.DeepL.com/Translator (free version)

**Comment by pimarc** [comment]
Hello
The best is to install the data MOD (https://pms50.com/fs2020/gns530/pms50-gns530-data.zip) and put the config.json file in to the Config\pms50-gns530 of this mod.

**Comment by tuxuera** [comment]
solved as you said, thank you very much for your help.
and as I said before very good job.
best regards

**Comment by pimarc** [comment]
I'm happy if this works for you.
