### ISSUE TITLE
GNS430 - Page groups in wrong order

### ISSUE THREAD

**Issue by dusty674** [pimarc/pms50-gns530#23]
Firstly - what an amazing job you have done. Thank you so much.

Two minor suggestions to more closely replicate the real world unit:
(1) On a real GNS430 the order of the 'Page Groups' is NAV, WPT, AUX, NRST where as in MSFS2020 it is appearing as NAV, WPT, NRST, AUX
(2) On a real GNS430 if the large nav knob is turned clockwise so that the last page group is selected, continuing to turn it clockwise should not change the page group. i.e. turning the knob clockwise 8 times should result in NAV, WPT, AUX, NRST, NRST, NRST, NRST, NRST, where as in the MSFS2020 it cycles back to the first page.

The reason this matters is that if your flying for real and have an emergency, you can just spin the large nav knob to the right and know that you'll be on the NRST page listing the 3 closest airports.

I'm no programmer, but I had a go at modifying your code to replicate the correct behaviour. It works for me but i haven't done any extensive testing and so I share it with you in the hope it provides a little bit of assistance. 

Thanks again for everything you have done.
Dusty

To correct issue 1 -
File: Packages\Community\pms50-gns530\html_ui\Pms50\Pages\VCockpit\Instruments\NavSystems\GPS\AS430\AS430.js
Line 75 - reordered the array elements.

        this.pageGroups = [
            new NavSystemPageGroup("NAV", this, [
                defaultNav,
                mapNav,
                terrainNav,
                trafficNav,
                new NavSystemPage("ComNav", "ComNav", new GPS_ComNav()),
                new NavSystemPage("Position", "Position", new GPS_Position()),
            ]),
            new NavSystemPageGroup("WPT", this, [
                new NavSystemPage("AirportLocation", "AirportLocation", new GPS_AirportWaypointLocation(this.airportWaypointsIcaoSearchField)),
                new NavSystemPage("AirportRunway", "AirportRunway", new GPS_AirportWaypointRunways(this.airportWaypointsIcaoSearchField)),
                new NavSystemPage("AirportFrequency", "AirportFrequency", new GPS_AirportWaypointFrequencies(this.airportWaypointsIcaoSearchField, 6)),
                new NavSystemPage("AirportApproach", "AirportApproach", new GPS_AirportWaypointApproaches(this.airportWaypointsIcaoSearchField)),
                new NavSystemPage("AirportArrival", "AirportArrival", new GPS_AirportWaypointArrivals(this.airportWaypointsIcaoSearchField)),
                new NavSystemPage("AirportDeparture", "AirportDeparture", new GPS_AirportWaypointDepartures(this.airportWaypointsIcaoSearchField)),
                new NavSystemPage("Intersection", "Intersection", new GPS_IntersectionWaypoint()),
                new NavSystemPage("NDB", "NDB", new GPS_NDBWaypoint()),
                new NavSystemPage("VOR", "VOR", new GPS_VORWaypoint())
            ]),
		new NavSystemPageGroup("AUX", this, [
                new NavSystemPage("COMSetup", "COMSetup", new GPS_COMSetup()),
                new NavSystemPage("METAR", "METAR", new GPS_METAR(this.airportWaypointsIcaoSearchField, 6))
            ]),
            new NavSystemPageGroup("NRST", this, [
                new NavSystemPage("NRSTAirport", "NRSTAirport", new GPS_NearestAirports()),
                new NavSystemPage("NRSTIntersection", "NRSTIntersection", new GPS_NearestIntersection()),
                new NavSystemPage("NRSTNDB", "NRSTNDB", new GPS_NearestNDB()),
                new NavSystemPage("NRSTVOR", "NRSTVOR", new GPS_NearestVOR()),
                new NavSystemPage("NRSTAirspace", "NRSTAirspace", new GPS_NearestAirpaces()),
            ])
        ];

To correct issue 2 - 
File: \Packages\Community\pms50-gns530\html_ui\Pms50\Pages\VCockpit\Instruments\NavSystems\Shared\NavSystem.js
Line 227 added additional IF statements 5 & 16 lines down:

	if (_event == "NavigationLargeInc") {
		 this.lastRelevantICAO = null;
		 this.lastRelevantICAOType = null;
		 if (this.pageGroups.length > 1 && !this.currentEventLinkedPageGroup) {
			if (this.currentPageGroupIndex < (this.pageGroups.length-1)) {
				this.pageGroups[this.currentPageGroupIndex].onExit();
				this.currentPageGroupIndex = (this.currentPageGroupIndex + 1) % this.pageGroups.length;
				this.pageGroups[this.currentPageGroupIndex].onEnter();
			}
		}
	}
	 if (_event == "NavigationLargeDec") {
		 this.lastRelevantICAO = null;
		 this.lastRelevantICAOType = null;
		 if (this.pageGroups.length > 1 && !this.currentEventLinkedPageGroup) {
			if (this.currentPageGroupIndex > 0) {							
				this.pageGroups[this.currentPageGroupIndex].onExit();
				this.currentPageGroupIndex = (this.currentPageGroupIndex + this.pageGroups.length - 1) % this.pageGroups.length;
				this.pageGroups[this.currentPageGroupIndex].onEnter();
			}
		}
	 }

**Comment by pimarc** [comment]
Thanks for that.
You give me the issue, the fix and the reason. Great.
I will include that for the next release.

**Comment by kmoze2001** [comment]
> I'm no programmer

You say that, and then proceed to provide the programming required to fix the problem.  I'd say that makes you a programmer lol...

I on the other hand, could NOT do what you just did.  Assuming your code works (and I'm the wrong person to check it), good job, and thank you from a community member.

**Comment by pimarc** [comment]
Case closed. The fix will be in the next release.
