### ISSUE TITLE
GNS 530 GNS 430 and All Radios 

### ISSUE THREAD

**Issue by drmiller21** [pimarc/pms50-gns530#24]
not functioning after I install the mod after last update to the sim after deleting mod all radios and GNS 530/430 come back on

**Comment by pimarc** [comment]
Are you sure you have downloaded the correct package?
This is typically what occurs when you download sources instead of the release.
Please remove the mod from the community folder and install the last release that you will find here:
https://pms50.com/fs2020/gns530/pms50-gns530.zip
Read carefully the installation steps in the documentation.

**Comment by drmiller21** [comment]
Hello

I downloaded the link at the top of the page that said latest version but I just downloaded the link you sent and I'll try it I'll let you know the result and thank you for the reply

Donald

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by drmiller21** [comment]
hello,

I downloaded the link you sent opened the file placed the correct folder to my community folder went in to the sim loaded a default 172 and all avionics off will not turn on deleted the folder out of the community folder went re-loaded the sim and aircraft and I had all my radios and GPS on now this situation did not start until the latest update

Donald
________________________________

**Comment by pimarc** [comment]
Should work. No issues here with the Cessna for other people.
If you have liveries or other mods, please try without them.

**Comment by drmiller21** [comment]
Hi

Thank you for getting back with me I'm not sure what is causing this issue when I put the PMS 50 - gns 530 plug in into community folder all my default aircraft all my payware aircraft radios and GPS units no longer turn on I take that file out I reboot the SIM and everything comes back on it did not do this before the last update I am not using any special plug-ins add-ons I do not have any add-on liveries

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pimarc** [comment]
Could you upload somewhere (google?) the zip file you have installed. I will check that.
For now I really don't know. If you install the correct file at the right place in the way described in the documentation and if you don't have any liveries or other MODs, this must work.

**Comment by BF529Q** [comment]
Hi there, I've download all the files and followed all instructions to the best of my ability. I'm using propwash 530 GPS, Audio Panel, One Radio with two actives/standby, and a transponder. Everything is powering up and loading however, once I get into the Cessna, it looks like only two buttons work on the 530. Com 1 and the CDI buttom. I dont have any other functionality. Maybe I missed a step? I have propwashfsx, but deleted the 530 port unplugged/pluggged back in. Using PWS530 adaptor and FSUIPC7 as well. I dropped the above file into community folder along with Mobiflight-event. Any guidance would be appreciated.

**Comment by BF529Q** [comment]
> Hi there, I've download all the files and followed all instructions to the best of my ability. I'm using propwash 530 GPS, Audio Panel, One Radio with two actives/standby, and a transponder. Everything is powering up and loading however, once I get into the Cessna, it looks like only two buttons work on the 530. Com 1 and the CDI buttom. I dont have any other functionality. Maybe I missed a step? I have propwashfsx, but deleted the 530 port unplugged/pluggged back in. Using PWS530 adaptor and FSUIPC7 as well. I dropped the above file into community folder along with Mobiflight-event. Any guidance would be appreciated.

Just a quick update, I restarted everything and once I started hitting the buttons on the 530 I got this error message. 
![Screenshot 2021-03-17 192640](https://user-images.githubusercontent.com/60526619/111552057-f2c78a80-8757-11eb-8119-f753f534a9c5.png)

**Comment by drmiller21** [comment]
Hello

I installed the correct file in the correct location unless the link you sent me is not correct I do not have any add-on livery's but will double check when I can get back to my system I will upload it to my Google drive and send you a link I will also double check my community folder to make sure there are no liveries as a measure to troubleshooting but I have gone through all the trouble shooting measures with Stan Anderson of flightSimbuilder  as I'm using his GPS GNS 530 bezel which is why I need this plugin
I do appreciate any help that you may be able to provide I will get it uploaded to my  as soon as possible thanks in advance

Donald


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by pimarc** [comment]
I'm sorry but I can't provide here support for external hardware or software that I do not own and manage.
Please try without any of them.
The error message is linked to FSUIPC that is not involved to use the GNS530 MOD.
I can suggest you contact the software/hardware vendors or post on the forums. Other users having similar configurations should help and you should help them in return.
Thank you also to remove the android links in your posted messages.

**Comment by drmiller21** [comment]
I appreciate that I'm not using fsuipc with your system and I did not send that message that was someone else I use flightSimbuilder builder GPS bezel and they uses your plug-n

This is my situation when I put your plug in into the community folder with no external plugins or add-ons none of the radios or GPS system works I delete your plug-in all works

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pimarc** [comment]
Ok so remove any hardware or external software here and try without it.
As I said, I cannot make support here if you use some external hardware because I cannot reproduce your environment.
Ask on the forums instead.
Thank you also to remove the android links in your posted messages. I have to remove them manually.

**Comment by drmiller21** [comment]
I think that we've got something confused here I'm not asking you for support for an external product or peripheral I'm asking you for support for your plug-in which every time I put it in my community folder breaks my sim when I delete it it unbreaks my sim. Has nothing to do with external plugins or external hardware and what is get rid of Android so I'll tell you what I'll do I appreciate your advice I appreciate your help I've been around flight SIM for 25 years I have been a developer for fs9 I am not new to the genre or to the situation I know what I'm doing and your plug-in has not worked properly since the last flight Sim 2020 update

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by antonvons** [comment]
I have noticed something similar. With this Mod, the gns530 or any other radios work for me either this is in the classic 172 or JF PA28R. But my issue seemed to be related to having the mod installed in a non default community folder and using MSFS Addons Linker to create symbolic links. Not sure if this is the problem or not, just like to know if Addons Linker can be used with this mod or not

**Comment by pimarc** [comment]
To drmiller,

My purpose is to help users but you should understand that I cannot reproduce the environment for each of them. That's why, when there is a potential bug, I ask to report it (see documentation) after having tested some things and especially having removed any other software and hardware that may produce some testing bias. This clean environment is absolutely necessary for me to qualify the bug and to try to fix it.
I think your problem is linked to your environment or to the installation of the MOD  since most other users do not have an issue here.
It may happen that external software or hardware drivers override some basic MSFS code that is used by the MOD so this one will not work.
So please test by temporarily removing any software or hardware, including installation software.

**Comment by pimarc** [comment]
To antonvons

I personally use symbolic links for managing my community folder so there is no issue here. Now using a third-party installation software may introduce a bias.

**Comment by drmiller21** [comment]
To Pimarc

I do understand the Fsbuilder bezel acts as a joystick controller for the Sim to see it Fsbuilder does have a plugin for MSFS Wich maps the buttons and knobs I will unplug it for that test and get back to you and see if a bug exsists in Fsbuilder 530 or in Gns 530 Gns plug  in I'm at work at the moment so it will be latter I have no other external items that work off  gps except siatek panels witch I use spad.next for witch has never affected my GPS  I do appreciate the help



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pimarc** [comment]
Ok

If you still have an issue with a clean environment and with only the GNS530 Mod in your community folder, please zip this community folder and send it to me via google drive or any other way so I can test that in my own clean environment.
If it works, just add your environment bricks one by one to try to identify a potential conflict.

**Comment by ammaloney** [comment]
Here's another data point.
I can replicate this behavior with the Carenado M20R installed.

**Comment by pimarc** [comment]
Can you upload somewhere this community folder in order for me to analyze the issue since I cannot reproduce it?

**Comment by ammaloney** [comment]
here is my community folder.
Hope it helps. Let me know if any other info will help.

Cheers
[Community.zip](https://github.com/pimarc/pms50-gns530/files/6177658/Community.zip)

**Comment by drmiller21** [comment]
To ammaloney,

thank you, sir, no longer experiencing this issue appreciate the help if it returns, I will post again thanks to all who replyed with advice

Donald
________________________________

**Comment by pimarc** [comment]
> here is my community folder.
> Hope it helps. Let me know if any other info will help.
> 
> Cheers

How did you install the Mod ?
Are you sure that the community folder you sent to me is the exact replication of yours?

This is because when I unzip your community files, the content of the mod folder is bad. All the files are in the root directories. There is no hierarchical structure.

**Comment by drmiller21** [comment]
I have not uploaded my community folder to this post so I don't know but appreciate it all the advice this thread can now be closed

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by pkoecker** [comment]
Hello everyone,

I do have the exact same issue but it only started today. Yesterday all was fine and I did not install any other new mods or anything like that. Very weird. So all avionics are turned off and refuse to turn on in all aircraft. When I remove the GNS 530 mod everything is back to normal. Put it back in and all avionics are broken again. 

I really appreciate all the work that went into this mod and I really hope that there is some solution to fix it.

I attached my community folder. Hope it helps.
[Community.zip](https://github.com/pimarc/pms50-gns530/files/6178181/Community.zip)

**Comment by pimarc** [comment]
I tested your community folder (and nothing else) with both the C172 and the Mooney. No problem at all. Everything works as expected.
I know that there is some issue on MSFS here as it is described in the release notes: https://forums.flightsimulator.com/t/release-release-notes-1-14-5-0-sim-update-iii-now-available/375519

But no problem here

Do you have external software or hardware related to MSFS ?

**Comment by pkoecker** [comment]
The only thing that runs in the background is Navigraph Simlink. As I said I did not change a thing and the issue occured from one day to another. Maybe it will be gone tomorrow? 
Thank you for all the effort though 👍

**Comment by ammaloney** [comment]
> > here is my community folder.
> > Hope it helps. Let me know if any other info will help.
> > Cheers
> 
> How did you install the Mod ?
> Are you sure that the community folder you sent to me is the exact replication of yours?
> 
> This is because when I unzip your community files, the content of the mod folder is bad. All the files are in the root directory. There is no hierarchical structure.
> 
> You should have this structure:
>

Huh! I don't know what munged my install, but after unzipping it again and making sure the directory structure was intact it works.

Thanks

**Comment by pimarc** [comment]
Good news. Thanks for your feedback and enjoy.

**Comment by pkoecker** [comment]
Hello again. Today I started Flight Simulator with the gns530 mod and it worked. Only yesterday, no matter how many restarts it refused to do so. Today, nothing changed in my community folder, everything works as expected.

**Comment by pimarc** [comment]
Now there is a known issue reported by Microsoft in the last update. Sometimes the GPS may fail to start. You just have to restart your flight.
Maybe this was your issue.
