### ISSUE TITLE
Weather radar not working

### ISSUE THREAD

**Issue by jakem1987** [pimarc/pms50-gns530#25]
Please explain it in retard terms I can't figure out how to get in to example_config and turn on the weather radar

**Comment by pimarc** [comment]
As explained in the documentation you must create the config.json file yourself by copying the example_config.json or renaming it in the same directory.
Then set this content to it:
{
  "weather_radar": "on",
  "weather_legend": "on",
  "metar_avwx_token": "",
  "metar_decode": "off"
}

Be careful to not have a comma after the last item (metar_decode here).

**Comment by jakem1987** [comment]
The problem is I don't know how to create a json file. I'm trying to do this right so it it works

**Comment by pimarc** [comment]
a json file is just a text file that you can create or edit with any text editor like notepad.
If you don't know how to create it, just rename the example_config.json file to config.json, open it with notepad and change the "off" values for the weather to "on" and save it. Then restart the sim.

**Comment by pimarc** [comment]
No feedback from the user so I close the case
