### ISSUE TITLE
For Issue #19 (GNS 430 is not turning on in Cessna 172)

### ISSUE THREAD

**Issue by Juanillus** [pimarc/pms50-gns530#27]
I had the same problem, the GNS 430 didnt turn on in Cessna 172, but the gns 530 did.

In my case, I solved it by starting cold from a general aviation ramp, and making the auto complete pages in the checklists.

Now it works fine, even starting in flight.

**Comment by pimarc** [comment]
Thanks for your feedback.
Probably the known issue described in the Asobo release notes: https://forums.flightsimulator.com/t/release-release-notes-1-14-5-0-sim-update-iii-now-available/375519
"On rare occasions, Aircraft screens might not initialize correctly upon loading a flight. Please restart the flight to fix the issue."

**Comment by avanrider** [comment]
I have the same issue with the Garmin not turning on (although in the Just Flight Piper Arrow, G430 and 530 both are black)
Restarting the flight does solve the issue, but annoying. Especially if I want to start cold and dark and forget...
