### ISSUE TITLE
ILS 27 approach EGLC with LCY transition not loading correctly 

### ISSUE THREAD

**Issue by TheFlyingDutchman77** [pimarc/pms50-gns530#30]
If I load the ILS 27 approach at EGLC with the LCY transition, a full circle should be loaded to enter the ILS approach (according to Little NavMap). However, the GNS530 is just putting in a half arc in the wrong direction. 

Btw: love the mod, thx for all your effort!!

**Comment by pimarc** [comment]
Did you try the same sequence without the MOD to with another GPS as suggested in the documentation "reporting a bug"?
I think this is not related to the MOD and you should get the same issue with another GPS.
The GPS just displays the sequence of points given by the sim's kernel.
Now when you reach your first waypoint approach with an important angle (ex 180°), the sim adds a great half circle. This is a normal situation even if the radius is calculated for a Boeing or an Airbus but not for a Cessna.
Please let me know.

**Comment by TheFlyingDutchman77** [comment]
OK, I thought your mod also modified the sims flight planner. But in that case, I'm quite sure it will be an issue for the flight planner of the sim, and not your mod. Apologies!
