### ISSUE TITLE
OBS line magenta turns white  1 mile beforeOBS WP

### ISSUE THREAD

**Issue by N6722C** [pimarc/pms50-gns530#31]
When OBS is activated,  the resulting magenta side of the bearing line,  does not reach the OBS WP.
Instead, it turns white about 1 mile early, resulting in an initial white bearing line  on the magenta side.

Particularly noticeable  when in full Zoom in.

**Comment by pimarc** [comment]
Yes. That's not an issue on the GNS503 code here but on the sim.
