### ISSUE TITLE
NAV view field VSR showing current vertical speed instead of vertical speed required

### ISSUE THREAD

**Issue by clompsy** [pimarc/pms50-gns530#32]
Selecting the field "VSR" in the main NAV page in the menu "Change Fields" results in the display of the current vertical speed in ft/s.
VSR is the abbreviation for Vertical Speed Required and should display the VSR value from the VNAV page as soon as a VNAV profile has been selected with the unit "f/m" and show underscores if no VNAV profile has been selected.

**Comment by pimarc** [comment]
It's already fixed as you can see in the changelog: https://github.com/pimarc/pms50-gns530#change-log
Will be available in next version.

**Comment by clompsy** [comment]
Oh sorry :) Thank you so much, I set it to closed then.
