### ISSUE TITLE
OBS angle not adjustable in Carenado PA28R

### ISSUE THREAD

**Issue by jrb737** [pimarc/pms50-gns530#33]
Adjustment of the HSI OBS, Nav 2 OBS, or "VOR 1 OBS" key binding do not effect an adjustment on the GNS530 in OBS mode while using the Carenado PA28R.

**Comment by pimarc** [comment]
Yes but the mechanical OBS is aircraft dependant. The cockpit builder must set the correct code here. I can't do anything on the GNS530 side. I've just added a way to do it from the 530 but it's not the standard way. The mechanical OBS should do the job.
