### ISSUE TITLE
OBS line

### ISSUE THREAD

**Issue by waterbass** [pimarc/pms50-gns530#34]
Hello , thanks for your work, I just want to add that, normally in a 530 the obs line would be rotating as we rotate the OBS. I can't manage to make it turn maybe is it on my side?
Have a Great day

**Comment by pimarc** [comment]
Yes but the mechanical OBS is aircraft dependant. The cockpit builder must set the correct code here. I can't do anything on the GNS530 side. I've just added a way to do it from the 530 but it's not the standard way. The mechanical OBS should do the job.
