### ISSUE TITLE
GPS freezing in JF Arrow

### ISSUE THREAD

**Issue by tailspin88** [pimarc/pms50-gns530#38]
Hello, After the latest SU4 this week, the GNS 530 freezes several minutes into flight in the JF Piper Arrow. The moving map freezes and the NAV and COM are not tunable once this happens. You can't switch the cursor between NAV and COM either. If you change the GNS selector to anything non-map (like airport info screens, fltplan, direct to) you can again tune NAV and COM and switch the cursor between them. When you go back to the map screen, everything is frozen and inop again. This is only on the GNS 530 unit, the GNS430 is completely fine and works perfectly. This is with the latest version of your GNS Mod installed.

I let the aircraft sit on the ground, engine running for an hour, and everything works fine. Once you takeoff, just a few minutes in it freezes up. So it only appears to happen once you're in the air. It doesn't matter if you start on the runway with the engine running or start at a parking spot, cold and dark, and then select 'ready for takeoff' in the JF tablet. The same issue with the GNS 530 unit occurs every time.

**Comment by pimarc** [comment]
Maybe you have not updated to the latest version compatible with sim update 4?

**Comment by tailspin88** [comment]
I have. I downloaded the newest version a few times just to be sure. Same freezing issue every time. I contacted JF but they said it's not their issue.

**Comment by tailspin88** [comment]
Am i supposed to download from the link that says 'latest download' or the master file? I've been downloading from the 'latest version' link, and not the master file. Thanks

**Comment by pimarc** [comment]
Ok very strange. Nobody reported any issue here and what you describe is what we have if not updated to the latest version.
What is the version number displayed on the GNS when you start it?

**Comment by tailspin88** [comment]
Okay I thought that was the same link on your github page a few sections down under 'latest release'. I'm downloading from the link you provided and will test and report back. Thanks for the help.

**Comment by tailspin88** [comment]
After a quick 5 min flight I don't have any issues anymore, Ill test further and let you know if I find anything wrong, but it looks good, thanks for the link. Usually within that time it would freeze so I'm assuming I'm good to go. Again, thanks for the help and quick reply. Flying with the default garmin is just not an option lol.
