### ISSUE TITLE
Sim freeze when entering waypoint on WPT page 7

### ISSUE THREAD

**Issue by matthboers** [pimarc/pms50-gns530#40]
Tested in Orbx EA-7 Edgley Optica with v1.0.34 installed. **Navigraph data is installed**. No further mods installed

Sim seems to freeze consistently when entering an intersection on the 7th page of the WPT category. Freeze tends to last quite long, I'd say for about half to a full minute.

To reproduce consistently, spawn in at TNCM and enter SUGNI. 
Can't quite say what causes this. I've tested at NZMF as well, as it is closer to the intersection in question. Same freeze as in TNCM. 

If anyone can confirm this is an issue on their system as well, greatly appreciated!

**Comment by pimarc** [comment]
Hi,

Yes this is a known issue but we can't do anything since it's at Asobo level.
Just don't go too fast with the knob for your first letter of the WP.

**Comment by matthboers** [comment]
Good to know it's already known. Hope they fix it soon!
I tried looking for a forum thread to upvote about this issue, but it could not find one. Is there a thread where I can vote for the issue to be fixed, or is it a known issue internally at Asobo?

In any case. If this bug is not with the mod itself, feel free to close the thread.
