### ISSUE TITLE
Saitek radio panel

### ISSUE THREAD

**Issue by symsei** [pimarc/pms50-gns530#41]
Hi !
I can't read and set the com frequency and nav frequency on my Logitech G Saitek Pro Flight Radio Panel
But you did a good job

**Comment by pimarc** [comment]
Hi
Thanks but not sure this is related to the Mod itself.

**Comment by symsei** [comment]
Hi
Unfortunely I tried With and without pns gns and thé leds dont Light on. But thé bottums are working. Without pas gns 530 all is correct.



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : pimarc ***@***.***>
Date : 13/06/2021 17:48 (GMT+01:00)
À : pimarc/pms50-gns530 ***@***.***>
Cc : symsei ***@***.***>, Author ***@***.***>
Objet : Re: [pimarc/pms50-gns530] Saitek radio panel (#41)


Hi
Thanks but not sure this is related to the Mod itself.
