### ISSUE TITLE
C172, mod PMS50-GNS530 and radiopanel Saitek , again 

### ISSUE THREAD

**Issue by symsei** [pimarc/pms50-gns530#43]
Hi!
I post this issue again , I apologize but this issue happens only when the mod is installed ; see below ;

I have a problem with this mod and my radiopanel saitek in the C172.
The leds do not light up, the buttons change the frequency well though.
Without this mod everything works correctly.
an idea ?

**Comment by pimarc** [comment]
Hi
I really don't know and I can't provide support for any external hardware that I don't own here.
The code of the Mod is open source so you can check it maybe.
