### ISSUE TITLE
direct to nearest

### ISSUE THREAD

**Issue by a402245** [pimarc/pms50-gns530#49]
Hello, this is not really a bug but more of a missing feature. I noticed that on the direct to page the "NRST" list is not implemented - is this intentional? Is this planned to be included in a future release? and congratulations on a very good mod for msfs - really great work!

**Comment by pimarc** [comment]
Thanks for your remark.
No, it's not implented yet. I have added it to the todo list.
For now, you can do the same by selecting the airport from the nearest pages and then press the direct To button.
