### ISSUE TITLE
Documentation Assistance

### ISSUE THREAD

**Issue by kmoze2001** [pimarc/pms50-gns530#5]
I thought you might find these helpful, though I suspect you have many of them already.  You could also distribute them with the mod itself if desired.

[Garmin 530 Quick Reference v. 190-00181-01-C.pdf](https://github.com/pimarc/pms50-gns530/files/5751978/Garmin.530.Quick.Reference.v.190-00181-01-C.pdf)
[Pimarc GNS530 Mod Instructions.docx](https://github.com/pimarc/pms50-gns530/files/5751981/Pimarc.GNS530.Mod.Instructions.docx)
[Pimarc GNS530 Mod Instructions.pdf](https://github.com/pimarc/pms50-gns530/files/5751983/Pimarc.GNS530.Mod.Instructions.pdf)
[GNS430 Quick Reference Guide.pdf](https://github.com/pimarc/pms50-gns530/files/5752007/GNS430.Quick.Reference.Guide.pdf)

**Comment by pimarc** [comment]
Thanks
