### ISSUE TITLE
Not showing up in simulator

### ISSUE THREAD

**Issue by jakem1987** [pimarc/pms50-gns530#50]
I'm having issues and inputting it into the SIM I dropped the file and unzipped in my community folder and it is not showing up when I turn the SIM on is there something I'm doing wrong

**Comment by pimarc** [comment]
Sorry I missed your ticket case.
Did you solve this issue?
If not, could you send me a screenshot of the content manager when searching for "GNS"
Thanks

**Comment by jakem1987** [comment]
Yes I figured it out and works, but I am however curious if you are able to see the name of highways like the actual gns?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pimarc** [comment]
No the road network in the sim is still very poor. We can do only with what the sim gives to us.
Maybe in the future.
