### ISSUE TITLE
GNS530 Adding Waypoints

### ISSUE THREAD

**Issue by aparsons671** [pimarc/pms50-gns530#51]
Recently, I flew a long flight from KSFB to KMGE in the Seneca.  As I was en-route, I programmed the GPS.  I loaded the flightplan into MSFS after loading up the sim at KSFB, so the flightplan wasn't available to load via the GPS itself.  I put in the first several waypoints (KIZER WORMS GUANO BARBS ROYES MATEO BRADO CRG HABLE BAXLY) and when putting in NEDRE, the list glitched to KIZER->WORMS and eliminated the rest of the waypoints.  By the time I got the waypoints back in, I was already on the way to GUANO, so I programmed GUANO BARBS ROYES MATEO BRADO CRG HABLE BAXLY NEDRE AILEY and when putting in DBN, it glitched again.  It seems when putting in a certain amount of waypoints, the list glitches and drops all but 3 of them.

Workaround was to just put in the turning points (KIZER CRG DBN WOGOM) and eliminate the intermediary waypoints.

**Comment by pimarc** [comment]
Hi
Adding waypoints is currently buggy in the sim (with any GPS) but I can't reproduce the issue you have.
Are you sure you have the latest version of the Mod (1.0.35)?
Did you test the same flight plan without the Mod? Could you do it if not,

**Comment by aparsons671** [comment]
confirmed 1.0.35

restarted pc and dumped navdata and all addons from community folder, reloaded navigraph data

loaded up KSFB parking 132 next to 9L departure end
started engines in seneca to avoid battery rundown
hit FPL, then right knob push for cursor

after each waypoint, waited for cursor to start flashing on final line for adding new waypoint before moving on
entered KIZER
entered WORMS
entered GUANO
entered BARBS

at this point, the flight plan ditched WORMS and GUANO leaving only KIZER and BARBS, similar to how it did last night.

moved input line to BARBS and put WORMS/GUANO back in
then added ROYES MATEO and went to add in BRADO and it took out MATEO leaving KIZER/WORMS/GUANO/BARBS/ROYES/BRADO without MATEO between ROYES/BRADO

I cannot seem to put in the flight plan fully and this is even without the autopilot engaged at all, just aircraft started, avionics master on to boot up gps and immediately start entering.

**Comment by pimarc** [comment]
So you have the same issue without the GNS530 Mod?

**Comment by aparsons671** [comment]
just completed the entire entry without the mod and no issues entering any waypoints...but damn i forgot how bad the default looked compared to the real thing...i mean your mod lol

**Comment by pimarc** [comment]
Do you have a pln file for the complete flight plan?

**Comment by pimarc** [comment]
Another question:
Do you enter the origin (KSFB) and the destination(KMGE) first ?

**Comment by pimarc** [comment]
I cannot reproduce that issue. Now I'm testing on the SU5 beta so maybe yo
![KSFB](https://user-images.githubusercontent.com/59776438/126399179-6a89afd4-4e28-4b43-a697-6cd6d135c144.jpg)
u can until the next sim update.

**Comment by aparsons671** [comment]
i have the complete pln now, but last night i didn't so had to manual enter...good thing i'm used to crap in airplanes not working right, so thinking outside the box no biggie lol...

first point i entered was kizer, then the rest as stated...if sim update 5 fixes this, I'm all for it...i'm also battling something on my pc from killing NTDLL.dll randomly causing all my programs to crash randomly, so there's that lol...i was lucky to get the flight in at all the gps issues being the least of my worries

**Comment by leecushing** [comment]
hello, just to add to this im getting the same problem with the mod. It sometimes randomly deletes all the waypoints ive entered.

**Comment by pimarc** [comment]
> hello, just to add to this im getting the same problem with the mod. It sometimes randomly deletes all the waypoints ive entered.

Thank you to give me a case that I can reproduce (the simplest possible one). Otherwise, I can't do anything.

**Comment by aparsons671** [comment]
weve got 4 days tim su5....hopefully this fixes the issues as youve stated you cannot reproduce and are on su5 beta while were on su4 release...
