### ISSUE TITLE
GNS430 - Loading of Flightplan not possible

### ISSUE THREAD

**Issue by CDrawe** [pimarc/pms50-gns530#52]
I'm using the GNS430 in the DC-6. It worked fine with the .35 release before. 
After the new MS Update 27.07.21 the .35 hasn't worked anymore. 
After loading the .36, the functionality has been restored, but the stored flightplans in the fpl530 folder wont show up and can't be loaded.

Any idea what is wrong?

**Comment by pimarc** [comment]
Maybe you can try with a standard aircraft (172 classic if you have it). That works correctly here.
Maybe you have deleted the fpl directory content where the flight plans reside when you have updated?

**Comment by CDrawe** [comment]
Unfortunately I don't have the C172 classic. The folder is in the correct place and has 12 entries. As mentioned before, it worked fine before the update.
Do I have any other chance to test it?

**Comment by CDrawe** [comment]
Tried it in the DA40 TDI - doesn't work

**Comment by pimarc** [comment]
We cannot reproduce that issue. Works perfectly in any aircraft here.
Verify that the pln files are at the correct place (especially if you have installed the pms50-gns530-data package). Check with only one file in the directory.

**Comment by CDrawe** [comment]
After installing your data package and placing the pln files in the folder in that directory, the flightplans are displayed. 
I would say, there is a bug in your software without the data package. 
Please try to check it!

**Comment by pimarc** [comment]
Ok so maybe a packaging issue. I will check that.

**Comment by pimarc** [comment]
We have rebuilt the package. Maybe you can try to redownload it and retry.
Be careful to empty your browser cache before downloading.

**Comment by CDrawe** [comment]
Deleted the old version and the data version as well. Installed the new downloaded package. 
Works well now.
Thank you very much.

**Comment by pimarc** [comment]
Thanks to you for your patience and your help.
I close the case.
