### ISSUE TITLE
After SU5, Activating Approach Forces ATC to 'Request Destination Change' (Original Airport)

### ISSUE THREAD

**Issue by DFWSupertrooper** [pimarc/pms50-gns530#53]
Since the latest release after SU5, any time I either _select_ an arrival, _select_ an approach, or _activate_ an approach, it triggers ATC to _Request Destination Change_ to the original airport (even if there is no change from the originally filed plan).  

I am curious if this is an Asobo issue to report on _all_ GNS430s or just the mod??  Not seeing anyone else reporting it in MSFS forum, I thought I'd try here first.

**Comment by pimarc** [comment]
The GPS is not concerned with ATC so this is probably a sim issue.
