### ISSUE TITLE
FPL disappears at approach waypoint - SU5

### ISSUE THREAD

**Issue by ecoleshill** [pimarc/pms50-gns530#54]
I did a flight into CYXU using the RNAV RWY 33 Z approach.   I did a Direct To KERPO and once I hit KERPO my FPL vanished.

I re-established on HDG, did a Direct to CYXU, selected and activated the approach again and then did a Direct To DAVOK before enabling NAV mode again.   Same problem.  Once the plane arrived at DAVOK the FPL was erased.

This only started happening after SU5 with the Hot Fix.

**Comment by pimarc** [comment]
Hi. Yes, there is a new bug in the Asobo code since SU5: the cancel direct to function removes the entire flight plan when an approach is loaded and the target directTO is part of the approach or is outside the FP).
I will try to find a workaround.

**Comment by pimarc** [comment]
A workaround has been set in latest release
