### ISSUE TITLE
Terrain map

### ISSUE THREAD

**Issue by Arcodacalheta** [pimarc/pms50-gns530#57]
Many thanks for your kind contribution to MSFS world of avionics.
I have been unable until now to show the terrain map on my Garmin 530. So I am wondering what I am doing wrong (I am far from being an expert with GPS, too old for that!): Your latest release is into my Community folder, and I am using the Cessna 172 to test, as well as the TB21 LionHeart. 
When toggling CLR I do see a scaling difference, but no relief colouring although I am on RWY25 in Sion Switzerland with plenty of high summits around me. 
I did restart my PC after installing your MOD. Originally I was using Add-on-Linker but opted to move your MOD to the Community folder thinking that perhaps something was not working correctly with AL. No joy!
Thank you for your help.

**Comment by Arcodacalheta** [comment]
Thank you for your reply. Unfortunately yes I do still have the issue. Presently on runway in Samedan and no way to see any colouring on the screen other than black and limits of TMA.
(both of course SU6 and latest mod downloaded today.

**Comment by pimarc** [comment]
We can't reproduce that issue. See attachment image
![2021-10-30 13_28_50-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/59776438/139531165-d8ed6531-4948-4b68-b4fc-6ce0f48f34e1.jpg)
t.

**Comment by Arcodacalheta** [comment]
Thank you for your feedback. I deleted my file and re-downloaded it, installed and restarted my PC, and then MSFS, I finally had access to the Terrain map as shown on your pictures above. I cannot figure what happened but I am happy that it now works!
Many thanks for your splendid work!
