### ISSUE TITLE
Waypoints get deleted when entering flight plan

### ISSUE THREAD

**Issue by Joeypilot** [pimarc/pms50-gns530#59]
Hello there,

I would like to report a bug in the gns530 that has made most of my flights rather frustrating. Every time I try to program my flight plan that I get from simbrief, I select a certain waypoint in my flight plan and press enter to load it into the GPS and for some reason it deletes either the waypoint that I programmed in before that one or the entire flight plan that came before that waypoint apart from the departure airport. I've had instances where I programmed in all of my waypoints and when I loaded in the arrival airport, my whole flight plan was deleted and I had to fly direct to the destination. There doesn't seem to be any sort of pattern in this issua, it just happens randomely. I am running the latest version of this mod as far as I know and I don't use any other mods for the default GPS system. I do hope this issue will be fixed in the next release because this bug makes the default gns430 a way better option to use since it has less bugs, at least from my experience. Not to hate on this mod though as I do think it has a ton of potential and it would be a fantastic mod if this issue and a couple of other bugs are resolved. 

Kind regards 
Joey Luyckx

**Comment by pimarc** [comment]
Hi Joey,
Thank you to give the exact steps to reproduce that issue.
Adding waypoints is still buggy in the sim. We tried to work around that but can't do it for all the cases. Sometimes the sim doesn't add the waypoint (or removes another one) into the flight plan especially if you have an approach loaded.
We also have a workaround to the famous u-turn (or flight back) MSFS bug that consists of removing all the enroute waypoints when you activate your approach.
Finally, a last MSFS bug deletes all the flight plan when you do a direct To an airport.

Also, be sure to have the latest version of the mod.

Kind regards
Pierre

**Comment by Joeypilot** [comment]
Hi there,

Since the last sim update I was forced to temporarily remove the mod from my community folder due to problems with my avionics. For some reason after the update many of the screens in almost every aircraft didn’t turn on anymore even though the avionics master switches were on. It seems to be an issue related mostly to the hardware that I use but it also has something to do with the mod because when I removed it from my folder the issue was resolved. Hopefully you are working on a new version for this mod as I thinks it’s a very good and much needed improvement for the default GPS but at the moment I am not able to use it.

Kind regards
Joey Luyckx

Verzonden vanuit Mail voor Windows

Van: pimarc
Verzonden: vrijdag 29 oktober 2021 18:01
Aan: pimarc/pms50-gns530
CC: Joeypilot; Author
Onderwerp: Re: [pimarc/pms50-gns530] Waypoints get deleted when entering flightplan (#59)

Hi Joey,
Do you still have the issue after SU6 and the latest Mod version?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pimarc** [comment]
Nobody has reported such an issue.
If you have honeycomb hardware, there is a known issue with some of their switches so try without.
