### ISSUE TITLE
Great mod!  Adding reference to M20R in game checklist you put together :)

### ISSUE THREAD

**Issue by davidjconnolly** [pimarc/pms50-gns530#6]
Great mod!  Thanks for putting this together.  I just wanted to suggest a reference to [the in-game checklist for the M20R](https://forums.flightsimulator.com/t/carenado-m20r-ovation-checklist-s/280126/5) that you also put together to make it easier to find (similar to what working title does with their mods).  Thanks for all your work, you've made the M20R so much more enjoyable to fly and I hope others will benefit from it as I have.

Maybe you could add this to a public GitHub repo so it's easy to track updates/contribute?

https://pms50.com/fs2020/carenado/m20r/carenado_m20r_checklist.zip

Thanks again!

**Comment by pimarc** [comment]
Hi,
For me the m20r checklist is a closed project. I have to send it now to Carenado for them to include it in their distribution.
