### ISSUE TITLE
Navigation error

### ISSUE THREAD

**Issue by Allex56** [pimarc/pms50-gns530#61]
Hello, Pimarc! I flew the route LDSP UMSOT ZRA SAL LDLO. I downloaded the Approach NDBDME-A LOS, transition EBITA procedure, but did not activate it. Before the ZRA waypoint, I activated Approach, but the autopilot did not fly to the first EBITA approach point, but flew to the last SAL waypoint. Only after reaching the SAL point, the autopilot flew to the EBITA point. There is the track here on LNM. Thanks for your job.
![про MOD GNS530](https://user-images.githubusercontent.com/91329575/134772325-7868b48a-1037-4652-9131-ae380d10550a.png)

**Comment by pimarc** [comment]
I think your first waypoint is not UMSOT but KEMIX.
Anyway, I tested your flight plan and didn't have any issue.
Activating the approach before ZRA, removes all the enroute waypoints as expected (U-turn bug workaround) and the next WP is EBITA.
