### ISSUE TITLE
No token. Check config

### ISSUE THREAD

**Issue by Donamy58** [pimarc/pms50-gns530#64]
I've registered on AVWX and entered the API token, but it doesn't seem to be seeing it. Does the config.json stay in the gns 530 folder ?

**Comment by romoni** [comment]
I have the same problem as Donamy58. I updatetd the GNS yesterday and after that the this problen started.

**Comment by pimarc** [comment]
The config file is named config.json and is located in the directory **Config/pms50-gns530** directory of the MOD.
If you update the Mod, the new version replaces the old config file so make a copy before or use the Data Mod (see the documentation chapter data MOD.

**Comment by romoni** [comment]
Hello!
Thank You pimark. Very odd but yestarday Metar Text didn't work - I tryed everything - but a few minutes ago I tested it again with PMDG's DS-6 and everything seems to be work again very well.
BTW Nice Mod!
