### ISSUE TITLE
GNS 530  not loading ILS Freq when Approach is activated. 

### ISSUE THREAD

**Issue by wothanfja16** [pimarc/pms50-gns530#7]
With certain airports, the ILS freq is not loaded when activating an ILS approach.

**Comment by pimarc** [comment]
Thank you to read that and provide the necessary information before submitting an issue
https://github.com/pimarc/pms50-gns530#bug-reporting

Without further information from you, we cannot help. Please give at least an example that can be reproduced (airport name, approach and transition, etc...).

**Comment by wothanfja16** [comment]
GNS530 version 1.024
Default Cessna C172 with oldstyle gauges and GNS530.
Route: EKEB-EKBI
EKBI Approach ILSY RWY27, UDINA Transition.
Approach activated 10 nm from UDINA.

Tried both Default Navdata and Navigraph AIRAC 2014

Other mods:
Workingtitle CJ4 v0.9.1, G-1000 v0.3.4, G-3000 v0.3.4

**Comment by pimarc** [comment]
I cannot reproduce the issue. The frequency 110.70 of the ILS 27 is correctly loaded in standby NAV. Please try without any MOD maybe ?
![ekbi](https://user-images.githubusercontent.com/59776438/104382907-45ee4880-552f-11eb-87e1-f9b195a2b254.jpg)

**Comment by wothanfja16** [comment]
Hi again

I just made some more tests.

I removed my 3rd party EKBI airport, thus using the default airport and now the ILS freq was correctly set.

I then tried with all my 3rd party airports (all installed in either the Packages/Community or
the Packages/Official folders) and none of them woul set the ILS freq.
Testing a handfull of nearby default MSFS airports, all of them worked fine.

So it seems that the problem is with all 3rd party airports, regardless whether they are installed inPackages/Community or
the Packages/Official folders.

**Comment by pimarc** [comment]
I'm using a standard asobo function to get the approach frequency. I didn't modify anything here.

The problem is probably on the third party airport providers. Do you have the frequency listed in the waypoint pages of the GNS530 ?

Maybe you should contact their support?

**Comment by pimarc** [comment]
Probably not related to the Mod
