### ISSUE TITLE
Sim hangs after operating either GPS control knob while showing the Metar (Origin/Destination) menu

### ISSUE THREAD

**Issue by paulwareing** [pimarc/pms50-gns530#8]
Great Mod!

MSFS v1.12.13.0
Mod v1.0.25
data MOD
config.json configured with AVWX token, and all other items to 'on'.
Metar retrieval works.  All functions work as expected & described (apart from this issue).
While on the Metar page I clicked the Menu button.  This shows a Metar Menu with 2 options - Origin & Destination.
IIRC both these options were greyed out.  Also IIRC correctly I didn't have a FPL set.  I probably didn't have either a destination or origin airport.
Under these conditions, and on 2 separate occasions, when I rotated the GPS knob (outer I think) as if I were going to scroll through the menu - the sim hung (no further graphical updates & no interaction ability) with the rotate cursor showing.  I left the simulator in this state for 2-3 minutes each time, before I eventually ended the MSFS task with task manager.

![hang](https://user-images.githubusercontent.com/8913887/105470890-04c60900-5c92-11eb-8805-a2bacd83a39c.PNG)

**Comment by pimarc** [comment]
Thanks for reporting that.
This is confirmed as a bug and will be fixed in next release.
As a workaround for now, just press the MENU button again instead of the ENT button if no origin or destination defined (or set them).
